FROM centos:centos7


RUN mkdir -p /src/sap_hana

COPY ./binary/hxe.tgz /src/sap_hana

WORKDIR /src/sap_hana

RUN tar -xzf hxe.tgz 

RUN yum install -y libaio numactl-libs libtool-ltdl gcc

#RUN ./setup_hxe.sh